spring.application.name=HumanLikeAutomationBot
spring.datasource.url=jdbc:postgresql://localhost:5432/humanbot
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=supersecretkeysupersecretkey123456
jwt.expiration=36000000